### ISSUE TITLE
Pokud chceme "slovník bez klíčů", je vhodné použít `set`

### ISSUE THREAD

**Issue by xtompok** [dancejod/prog2_du02#6]
pokud potřebujeme datovou strukturu, které se budeme ptát jestli v ní daná položka je a budeme do ní chtít vkládat nejvýš jeden exemplář od každé položky, tak je to `set`, který obě operace umí rychle a je na toto vhodnější než obyčejný seznam.

**Comment by dancejod** [comment]
Kde presne to myslis?

**Comment by xtompok** [comment]
Všude, kde se vyskytuje konstrukce "Pokud není objekt `a` v seznamu `b`, tak ho tam přidej", tedy jmenovitě v přidávání do `routes`, dá se to použít i v `daterange` a možná ještě někde.
